### ISSUE TITLE
カタログ更新（観光情報）

### ISSUE THREAD

**Issue by hkwi** [City-of-Kobe/opendata#11]
ckan_url
https://data.city.kobe.lg.jp/data/dataset/dataset-00000005

ですが、更新漏れを見つけました。

旧 http://www.city.kobe.lg.jp/information/project/industry/img/tourism_od2707.csv
新 http://www.city.kobe.lg.jp/information/project/industry/img/tourism_od2810.csv

**Comment by ictsozo02** [comment]
ご指摘ありがとうございます。
遅くなりましたが、対応しました。
