### ISSUE TITLE
カタログ更新（まちかど救急ステーション）

### ISSUE THREAD

**Issue by hkwi** [City-of-Kobe/opendata#13]
ckan_url
https://data.city.kobe.lg.jp/data/dataset/dataset-00000003

ですが、更新漏れを見つけました。

旧 http://www.city.kobe.lg.jp/safety/fire/ambulance/aedmap/aed--_kobe.xml
新 http://www.city.kobe.lg.jp/safety/fire/aed_kobe.xml

**Comment by ictsozo02** [comment]
ご指摘ありがとうございます。対応しました。
