### ISSUE TITLE
[リンクミス]平成27年度放射性物質の毎月検査結果 平成28年1月

### ISSUE THREAD

**Issue by hkwi** [City-of-Kobe/opendata#17]
https://data.city.kobe.lg.jp/data/dataset/dataset-00000117/resource/2de34a88-9332-492b-b2a1-5779dfc70213

データの URL が一覧ページになっています。
正：http://www.city.kobe.lg.jp/life/town/waterworks/water/suishitu/3H28_1.pdf
誤：http://www.city.kobe.lg.jp/life/town/waterworks/water/suishitu/02_3H27.html

**Comment by ictsozo02** [comment]
修正しました。
ご連絡ありがとうございました。
