### ISSUE TITLE
[広報誌 html 2015年11月号] 作業漏れ？の修正

### ISSUE THREAD

**Issue by hkwi** [City-of-Kobe/opendata#5]
「市政情報（講演・講習）」の「国際展示場」の日時が分割作業漏れしているようです。紙の広報誌では一つの囲みになっていたので、おそらく分割する際の作業漏れかと思います。

具体的には https://github.com/hkwi/kobe-opendata/pull/1 こんな感じです。

github はツール上の制約で、行単位が細かいほど扱いやすいのですが、このように一行が長いと少し見づらいですね…。

**Comment by ictsozo02** [comment]
修正完了しました。
ご指摘ありがとうございました。
http://www.city.kobe.lg.jp/information/public/kouhoushi/2015/1511/info04.html

**Comment by hkwi** [comment]
お手数をおかけいたしました。ありがとうございます。
