### ISSUE TITLE
毎月推計人口（平成27年10月）

### ISSUE THREAD

**Issue by hkwi** [City-of-Kobe/opendata#7]
月別の人口データですが、平成27年10月のデータが欠損しているようです（市ページ上）。
http://www.city.kobe.lg.jp/information/data/statistics/toukei/jinkou/suikeijinkou.html#midashi72481

いっぽう、ckanのカタログには登録がありますが、実際のデータが存在しないので取得に失敗します。
https://data.city.kobe.lg.jp/data/dataset/dataset-00000019/resource/c954e6c2-a329-457b-a899-53ec7e845523

実はデータがあるのか、はたまたデータを取り損ねたので、カタログデータが要修正なのか判断がつきませんが、報告いたします。

**Comment by ictsozo02** [comment]
ご連絡ありがとうございます。
平成27年10月分の毎月推計人口データは作成していません。
※国勢調査で調査しているためです。

データセットの説明文とリソースを修正しました。
https://data.city.kobe.lg.jp/data/dataset/dataset-00000019

**Comment by hkwi** [comment]
ご回答ありがとうございます。

ただ…平成27年9月分の区別の出生、死亡、転入、転出のデータが再現できなくて困ったのですが、どこか別のところにございますでしょうか？

**Comment by hkwi** [comment]
おぉ、[平成27年10月分も](http://www.city.kobe.lg.jp/information/data/statistics/toukei/jinkou/suikeijinkou.html)再計算して埋めていただいたようで、担当者様ありがとうございます。お手数をおかけいたしましたが、助かりました。ということは…カタログには再度登録ということで…すみません、よろしくお願いいたします、、

**Comment by ictsozo03** [comment]
カタログサイトへの登録も完了しました。
確認お願いします。

**Comment by hkwi** [comment]
ありがとうございます。ばっちりです。
