### ISSUE TITLE
平成28年 毎月推計人口

### ISSUE THREAD

**Issue by hkwi** [City-of-Kobe/opendata#8]
神戸市のページには平成 28 年 1, 2, 3 月のデータが掲載されていますが、https://data.city.kobe.lg.jp/ 側ではまだ登録されていないようです。
http://www.city.kobe.lg.jp/information/data/statistics/toukei/jinkou/suikeijinkou.html

**Comment by ictsozo03** [comment]
ご指摘ありがとうございます。
先ほどアップさせていただきました。」

**Comment by hkwi** [comment]
ありがとうございます！

と、同時に気が付いてしまいました…。[平成28年 毎月推計統計](https://data.city.kobe.lg.jp/data/dataset/dataset-00000020) という名前で `jinkou2801.xls` だけが重複登録されているということに…「平成28年 毎月推計人口」と書きたかったココロだったと思います、、

**Comment by ictsozo03** [comment]
ありがとうございます。平成２８年毎月推計統計は削除しておきました！

**Comment by hkwi** [comment]
確認しました～ +1
